# config.yaml
data:
  csv_path: "../../../data/processed_data/dataset.csv"
  feature_cols:
    - Barometer
    - TempIn
    - HumIn
    - TempOut
    - WindSpeed
    - HumOut
    - WindDir_sin
    - WindDir_cos
  target_cols:
    - RainRate
  input_window: 24 # steps
  output_window: 6 # steps

training:
  batch_size: 16
  learning_rate: 0.001
  epochs: 25
  device: "cpu"
  rounds: 20

model:
  input_dim: 6 
  output_dim: 1           
  d_model: 64             
  nhead: 4
  num_layers: 2
  dropout: 0.1