# config.yaml
data:
  csv_path: "../../../data/processed_data/dataset.csv"
  feature_cols:
    - barometer
    - temperature
    - wind_speed
    - rain_rate
    - hour_sin
    - hour_cos
    - month_sin
    - month_cos
  target_cols:
    - rain_rate
  input_window: 12 # steps
  output_window: 6 # steps

training:
  batch_size: 16
  learning_rate: 0.0003
  epochs: 5
  device: "cpu"
  rounds: 75

model:
  input_dim: 8
  output_dim: 1           
  d_model: 128           
  nhead: 4
  num_layers: 4
  dropout: 0.25